services:
  log-parser:
    build:
      context: .
      dockerfile: Dockerfile
    image: log-parser:latest
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./reports:/app/reports
    command: ["--config","config/config.yaml"]
